---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kmgm-issuer.coe.ad.jp
  resources:
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kmgm-issuer.coe.ad.jp
  resources:
  - issuers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kmgm-issuer.coe.ad.jp
  resources:
  - kmgmprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kmgm-issuer.coe.ad.jp
  resources:
  - kmgmprofiles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kmgm-issuer.coe.ad.jp
  resources:
  - kmgms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kmgm-issuer.coe.ad.jp
  resources:
  - kmgms/status
  verbs:
  - get
  - patch
  - update
