apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: kmgm-issuer
build:
  artifacts:
  - image: ghcr.io/ipa-cyberlab/kmgm-issuer
    ko:
      main: ./
  - image: ghcr.io/ipa-cyberlab/kmgm
    ko:
      main: github.com/IPA-CyberLab/kmgm/cmd/kmgm
  tagPolicy:
    sha256: {}
manifests:
  helm:
    releases:
    - name: kmgm
      chartPath: ./charts/kmgm-issuer
      namespace: kmgm
      recreatePods: true
deploy:
  helm:
    releases:
    - name: kmgm
      setValueTemplates:
        issuer.image.repository: "{{.IMAGE_REPO_ghcr_io_ipa_cyberlab_kmgm-issuer}}"
        issuer.image.tag: "{{.IMAGE_TAG_ghcr_io_ipa_cyberlab_kmgm-issuer}}@{{.IMAGE_DIGEST_ghcr_io_ipa_cyberlab_kmgm-issuer}}"
        kmgm.image.repository: "{{.IMAGE_REPO_ghcr_io_ipa_cyberlab_kmgm}}"
        kmgm.image.tag: "{{.IMAGE_TAG_ghcr_io_ipa_cyberlab_kmgm}}@{{.IMAGE_DIGEST_ghcr_io_ipa_cyberlab_kmgm}}"
