{{- if .Values.clusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kmgm-issuer.clusterRoleName" . }}
  labels:
    {{- include "kmgm.labels" . | nindent 4 }}
  {{- with .Values.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
{{ (.Files.Get "controller-gen/role.yaml" | fromYaml).rules | toYaml }}
{{- end }}
