apiVersion: v1
kind: Service
metadata:
  name: {{ include "kmgm.fullname" . }}
  labels:
    app.kubernetes.io/component: kmgm
    {{- include "kmgm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 34680
    protocol: TCP
  selector:
    app.kubernetes.io/component: kmgm
    {{- include "kmgm.selectorLabels" . | nindent 4 }}
