apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kmgm.fullname" . }}
  labels:
    app.kubernetes.io/component: kmgm
    {{- include "kmgm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kmgm
      {{- include "kmgm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: kmgm
        {{- include "kmgm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: kmgm
        args:
        - serve
        - --bootstrap-token-file
        - /etc/kmgm-token/token
        - --expose-metrics
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.kmgm.image.repository }}:{{ .Values.kmgm.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.kmgm.image.pullPolicy }}
        env:
        - name: KMGMDIR
          value: /var/lib/kmgm
        ports:
        - name: http
          containerPort: 34680
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTPS
        volumeMounts:
        - name: profile-vol
          mountPath: /var/lib/kmgm
        - name: token-vol
          mountPath: /etc/kmgm-token
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: token-vol
        secret:
          secretName: {{ include "kmgm.tokenSecretName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: profile-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
