on: [push, pull_request]
name: Test and Release
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '>= 1.15.5'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install kubebuilder
      run: |
        curl -sL https://go.kubebuilder.io/dl/${VERSION}/linux/amd64 | tar -xz -C ${{ github.workspace }}
        (cd ${{ github.workspace }} && ln -s kubebuilder_${VERSION}_linux_amd64 kubebuilder)
      env:
        VERSION: 2.3.1
    - name: Test
      run: go test ./...
      env:
        KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
  release:
    needs: [unit_tests]
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    steps:
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.iou
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags:
            ghcr.io/${{ github.repository_owner }}/kmgm-issuer:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
