on: [push, pull_request]
name: Test and Release
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '>= 1.15.5'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install kubebuilder
      run: |
        curl -sL https://go.kubebuilder.io/dl/${VERSION}/linux/amd64 | tar -xz -C ${{ github.workspace }}
        (cd ${{ github.workspace }} && ln -s kubebuilder_${VERSION}_linux_amd64 kubebuilder)
      env:
        VERSION: 2.3.1
    - name: Test
      run: go test ./...
      env:
        KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
  release:
    needs: [unit_tests]
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '>= 1.15.5'
      - name: Checkout
        uses: actions/checkout@v2
