on: [push, pull_request]
name: Test and Release
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '>= 1.15.5'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install kubebuilder
      run: |
        curl -sL https://go.kubebuilder.io/dl/${VERSION}/linux/amd64 | tar -xz -C ${{ github.workspace }}
        (cd ${{ github.workspace }} && ln -s kubebuilder_${VERSION}_linux_amd64 kubebuilder)
      env:
        VERSION: 2.3.1
    - name: Test
      run: go test ./...
      env:
        KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
  publish_docker_image:
    needs: [unit_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/ipa-cyberlab/kmgm-issuer
          tag-sha: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
